# Site settings
title: "Jeen Mathew"
email: jeenmathew26@gmail.com
description: "Website"
baseurl: ""
url: "https://iamjmat.github.io/"
github_repository: https://github.com/iamjmat/iamjmat.github.io/


# Social usernames/URLs
twitter_username: wunderjeenie
github_username:  iamjmat
hackerrank_username: https://www.hackerrank.com/iamjmat
linkedin_link: https://www.linkedin.com/in/iamjmat/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
