# Site settings
title: "Jeen Mathew"
email: jeenmathew26@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://iamjmat.github.io/"
github_repository: https://github.com/iamjmat/iamjmat.github.io/


# Social usernames/URLs
twitter_username: wunderjeeenie
github_username:  iamjmat
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: "&lt;/&gt; on <a href=\"https://github.com/wunderjeeenie/\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
